# Generated by Django 5.1 on 2025-11-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lavanderia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='empleados',
        ),
        migrations.AddField(
            model_name='empleado',
            name='servicios',
            field=models.ManyToManyField(related_name='empleados', to='app_lavanderia.servicio'),
        ),
    ]
