# Generated by Django 5.1 on 2025-11-20 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lavanderia', '0003_producto_proveedor_pedido_producto_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='producto_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedores_principales', to='app_lavanderia.producto'),
        ),
    ]
